project:
  type: book

book:
  title: "R for Mass Spectrometry"
  author: "Norah Jones"
  date: "5/12/2025"
  chapters:
    - index.qmd
    - introduction.qmd
    - 01-r-fundamentals.qmd
    - 02-data-formats-import.qmd
    - 03-spectral-preprocessing.qmd
    - 04-peak-detection-quantification.qmd
    - 05-data-visualization.qmd
    - 06-statistical-analysis.qmd
    - 07-metabolomics-analysis.qmd
    - 08-proteomics-analysis.qmd
    - 10-qfeatures-quantitative.qmd
    - 09-advanced-topics.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

execute:
  warning: false
  message: false
  echo: true

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

